version: '3'
services:

  # If you want to test the application in docker and not on localhost
  # IMO this should be done in the latest stages of the project
  go:
    build:
        context: src
        dockerfile: docker/Dockerfile
    environment:
      - PORT=80
