version: '3'
services:

  # If you want to test the application in docker and not on localhost
  # IMO this should be done in the latest stages of the project
  go:
    depends_on: 
      - redis
    build:
        context: src
        dockerfile: docker/Dockerfile
    ports:
      - 8080:80
    environment:
      - REDIS_HOST=redis
      # - REDIS_PORT=6379

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379