version: '3'
services:

  chinook:
    image: battlesable/chinook:postgres-10-alpine
    ports:
      - "5432:5432"

  pg-admin:
      image: dpage/pgadmin4
      ports:
        - "9000:80"
      environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
      volumes:
        - ${PWD}/servers.json:/pgadmin4/servers.json

  # If you want to test the application in docker and not on localhost
  # IMO this should be done in the latest stages of the project
  go:
    depends_on:
      - chinook
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PORT=80
      - DB_HOST=chinook
      - DB_USER=postgres
      - DB_PASSWORD=chinook
      - DB=chinook
