version: '3'
services:
  chinook:
    image: battlesable/chinook:postgres-10
    ports:
      - "5432:5432"
  pg-admin:
      image: dpage/pgadmin4
      ports:
        - "9000:80"
      environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
      volumes:
        - ${PWD}/servers.json:/pgadmin4/servers.json
  go:
    image: battlesable/chinook:postgres-10
    ports:
      - "5432:5432"